#!/bin/sh

RUNDIR=`pwd`
LOC="/home/zenol/developpez/kit"

if [[ $1 != "" ]]
then
    NAME="${1%.*}"
    echo "---------- XML VALIDATION ----------"
    VALIDATE=`xmllint --noout --schema  $LOC/xsd/article.xsd $NAME.xml`
    echo "------------------------------------"
else
    echo $0 " article_name.xml"
fi
