#!/bin/sh
pandoc --gladtex --no-highlight | sed "s/<span class=\"..\">//g" | sed "s/<\/span>//g" | sed "s/<\/code><\/pre>/<\/pre>/g" | sed "s/<pre class=\"sourceCode \([a-zA-Z]*\)\"><code class=\"sourceCode cpp\">/<pre lang=\"\1\" colla=\"+\">/g" | sed "s/&#39;/'/g" | sed "s/&amp;/\&/g"  | sed "s/&lt;/</g" | sed "s/&quot;/\"/g" | sed "s/&gt;/>/g"
# Usage : "markdown2wordpress < input > output" or cat "input | markdown2wordpress > output"
